build:
	g++ main.cpp mqtt_client.cpp db_accessor.cpp msg_processor.cpp event_handler.cpp -lpaho-mqttpp3 -lpaho-mqtt3as -lpthread -lmysqlcppconn -I/usr/local/include -I/usr/local/include/cppconn -o main
